# Updated for Code Server: https://github.com/nils-braun/codehub/
# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://hub.jupyter.org/helm-chart/
# Configure Github OAuth    https://z2jh.jupyter.org/en/stable/administrator/authentication.html#github
#
singleuser:
  allowPrivilegeEscalation: true
  fsGid: 1000
  image:
    name: jupyter/minimal-notebook
    tag: latest
  storage:
    homeMountPath: "/home/coder"
    extraVolumes:
      - name: docker-certs
        emptyDir: {}
    extraVolumeMounts:
      - name: docker-certs
        mountPath: /certs
    
  profileList:
      - display_name: "VSCode Remote - Custom Base"
        description: "Remote VS Code Environment"
        kubespawner_override:
          image: ghcr.io/hashtagcyber/codeserver-base:latest
          imagePullSecrets: ["ghcr"]
          cmd: ""
          extra_containers:
            - name: docker-dind-sidecar
              image: docker:dind
              imagePullPolicy: IfNotPresent
              securityContext:
                privileged: true
              volumeMounts:
                - name: docker-certs
                  mountPath: /certs
          environment:
            DOCKER_HOST: "tcp://localhost:2376"
            DOCKER_CERT_PATH: "/certs/client"
            DOCKER_TLS_VERIFY: "1"

proxy:
  chp:
    # Make sure the code server does never get to know about
    # the user-specific prefixes and thinks "it runs by itself"
    extraCommandLineFlags:
    - "--no-include-prefix"

hub:
  config:
    Authenticator:
      admin_users:
        - hashtagcyber
    GitHubOAuthenticator:
      oauth_callback_url: https://jupyter.totallylegitsite.com/hub/oauth_callback
      allowed_organizations:
        - secengbootcamp
      scope:
        - read:org
    JupyterHub:
      authenticator_class: github