name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'dockerfiles/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Changed Directories
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^dockerfiles/' | awk -F'/' '{print $2}' | sort -u)
          echo "CHANGED_DIRS=$CHANGED_DIRS" >> $GITHUB_ENV

      - name: Build and Push Docker Images
        run: |
          COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          for dir in $CHANGED_DIRS
          do
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$dir:latest
            IMAGE_NAME_SHA=ghcr.io/${{ github.repository_owner }}/$dir:$COMMIT_SHA
            docker build -t $IMAGE_NAME -t $IMAGE_NAME_SHA ./dockerfiles/$dir/
            docker push $IMAGE_NAME
            docker push $IMAGE_NAME_SHA
          done

