name: Deploy Helm Chart

on:
  push:
    paths:
      - 'helm/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Kubernetes context
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Add JupyterHub Helm repository
        run: |
          helm repo add jupyterhub https://hub.jupyter.org/helm-chart/
          helm repo update

      - name: Deploy Helm Chart
        run:  helm upgrade --cleanup-on-fail --install jupyter-experimental jupyterhub/jupyterhub --namespace jupyter --create-namespace --version=3.2.1 --values helm/config.yaml --timeout 10m0s --set hub.config.GitHubOAuthenticator.client_id=${{ secrets.JUPYTER_GH_CLIENT_ID }},hub.config.GitHubOAuthenticator.client_secret=${{ secrets.JUPYTER_GH_CLIENT_SECRET }},proxy.secretToken=${{ secrets.JUPYTER_CODER_SEED }}